name: 'Deploy CloudFormation Stack'
description: 'Downloads template, maps parameters, and deploys stack'

inputs:
  stack_name:
    required: true
  template_artifact:
    description: "Name of the GitHub Artifact containing the template"
    required: true
  template_filename:
    description: "Filename inside the artifact (default: patched-template.json)"
    required: false
    default: "patched-template.json"
  flavor:
    description: "Deployment flavor (e.g., ps-linux)"
    required: true
  region:
    required: true
  # Dynamic inputs that need to be mapped to specific params
  vpc_id:
    required: true
  subnet_id:
    required: true
  key_name:
    required: true
  ami_id:
    description: "Custom AMI ID to inject"
    required: false

outputs:
  stack_outputs:
    description: "JSON string of stack outputs"
    value: ${{ steps.outputs.outputs.STACK_OUTPUTS }}

runs:
  using: "composite"
  steps:
    # --- NEW STEP: Self-contained Download ---
    - name: Download Template
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.template_artifact }}
        path: ${{ runner.temp }}/cfn-deployment

    - name: Validate Inputs
      shell: bash
      run: |
        if [[ -z "${{ inputs.flavor }}" ]]; then
          echo "::error::Input 'flavor' is empty. Please check your workflow configuration."
          exit 1
        fi

    - name: Prepare Parameters JSON
      id: prep-params
      shell: bash
      env:
        FLAVOR: ${{ inputs.flavor }}
        VPC: ${{ inputs.vpc_id }}
        SUBNET: ${{ inputs.subnet_id }}
        KEY: ${{ inputs.key_name }}
        AMI: ${{ inputs.ami_id }}
        # Use github.action_path to find the bundled config file
        CONFIG_FILE: "${{ github.action_path }}/flavor-mappings.json"
      run: |
        # Read the mapping config
        CONFIG_FILE="${{ github.action_path }}/flavor-mappings.json"
        
        # Extract variable parameter names for this flavor
        KEY_PARAM=$(jq -r ".\"$FLAVOR\".key_param" $CONFIG_FILE)
        VPC_PARAM=$(jq -r ".\"$FLAVOR\".vpc_param" $CONFIG_FILE)
        SUBNET_PARAM=$(jq -r ".\"$FLAVOR\".subnet_param" $CONFIG_FILE)
        IMAGE_PARAM=$(jq -r ".\"$FLAVOR\".ami_param" $CONFIG_FILE)
        
        jq ".\"$FLAVOR\".defaults" $CONFIG_FILE > params.json
        
        # We use a temp file (tmp.json) to allow iterative jq updates

        # Inject VPC
        jq --arg k "$VPC_PARAM" --arg v "$VPC" '. += [{"ParameterKey": $k, "ParameterValue": $v}]' params.json > tmp.json && mv tmp.json params.json
        
        # Inject Subnet
        jq --arg k "$SUBNET_PARAM" --arg v "$SUBNET" '. += [{"ParameterKey": $k, "ParameterValue": $v}]' params.json > tmp.json && mv tmp.json params.json
        
        # Inject Key
        jq --arg k "$KEY_PARAM" --arg v "$KEY" '. += [{"ParameterKey": $k, "ParameterValue": $v}]' params.json > tmp.json && mv tmp.json params.json
        
        # Inject AMI
        if [[ -n "$AMI" ]]; then
          jq --arg k "$IMAGE_PARAM" --arg v "$KEY" '. += [{"ParameterKey": $k, "ParameterValue": $v}]' params.json > tmp.json && mv tmp.json params.json
        fi
        
        # --- add additional params here ---
        # ----------------------------------

        echo "Generated Parameters:"
        cat params.json

    - name: Deploy Stack
      shell: bash
      run: |
        # Construct path to the downloaded file
        TEMPLATE_FILE="${{ runner.temp }}/cfn-deployment/${{ inputs.template_filename }}"
        
        if [[ ! -f "$TEMPLATE_FILE" ]]; then
          echo "::error::Template file not found at $TEMPLATE_FILE"
          ls -R ${{ runner.temp }}/cfn-deployment
          exit 1
        fi

        aws cloudformation create-stack \
          --stack-name ${{ inputs.stack_name }} \
          --template-body file://"$TEMPLATE_FILE" \
          --region ${{ inputs.region }} \
          --capabilities CAPABILITY_NAMED_IAM CAPABILITY_IAM \
          --parameters file://params.json

        echo "Waiting for stack creation..."
        aws cloudformation wait stack-create-complete \
          --stack-name ${{ inputs.stack_name }} \
          --region ${{ inputs.region }}

    - name: Retrieve Stack Outputs
      id: outputs
      shell: bash
      run: |
        # Get Outputs as a simplified JSON object { "OutputKey": "OutputValue" }
        OUTPUTS=$(aws cloudformation describe-stacks \
          --stack-name ${{ inputs.stack_name }} \
          --region ${{ inputs.region }} \
          --query "Stacks[0].Outputs" | \
          jq -c 'reduce .[] as $item ({}; . + {($item.OutputKey): $item.OutputValue})')
        
        echo "STACK_OUTPUTS=$OUTPUTS" >> $GITHUB_OUTPUT