name: 'Create AWS Template'
description: 'Generates a CloudFormation template by injecting a RegionMap.'

inputs:
  region_map:
    description: 'JSON object string for RegionMap'
    required: true
  output_filename:
    description: 'Filename for the generated template'
    required: true
  artifact_name:
    description: 'Name of the artifact to upload to GH'
    required: true   
  metatemplate_file_path:
    description: 'Path to the source JSON meta-template file'
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate Template
      shell: bash
      env:
        TEMPLATE: ${{ inputs.metatemplate_file_path }}
        REGION_MAP: ${{ inputs.region_map }}
        OUT_NAME: ${{ inputs.output_filename }}
      run: |
        # 1. Install jq if missing
        if ! command -v jq &> /dev/null; then
            echo "jq not found, installing..."
            sudo apt-get update && sudo apt-get install -y jq
        fi

        echo "Injecting Region Map into template..."

        # 2. Write input JSON string to temp file for safe handling
        echo "$REGION_MAP" > region_map_temp.json

        # 3. Inject the map into .Mappings.RegionMap
        # This replaces whatever is currently in Mappings.RegionMap
        jq --slurpfile map region_map_temp.json \
           '.Mappings.RegionMap = $map[0]' \
           "$TEMPLATE" > "$OUT_NAME"

        rm region_map_temp.json

        echo "Generated: $OUT_NAME"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.output_filename }}