name: 'Run Smoke Tests'
description: 'Run smoke Tests'

inputs:
  region:
    description: 'AWS Region'
    required: true
  stack_name:
    description: 'CloudFormation Stack Name'
    required: true
  matlab_license_string:
    description: 'MATLAB License String'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r tests/e2e/requirements.txt

    - name: Run Pytest
      shell: bash
      env:
        MATLAB_LICENSE_STRING: ${{ inputs.matlab_license_string }}
      run: |
        pytest tests/e2e \
          --stack-name="${{ inputs.stack_name }}" \
          --aws-region="${{ inputs.region }}"
